services:
  web:
    image: chronovortex07/react-web:localhost
    ports:
      - "3000:3000"
    # environment:
    #   VITE_API_ENDPOINT: http://app.labassist.live:5500/
    depends_on:
      - api
      - redis
      - celery-worker

  api:
    image: chronovortex07/flask-api:localhost
    ports:
      - "5500:5500"
    environment:
      SECRET_KEY: "secret"
      DEBUG_MODE: True
      UPLOAD_FOLDER: /uploads
      CLEANUP_UPLOADS: False
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_TASK_TRACK_STARTED: True
      CELERY_TRACK_STARTED: True
      SOCKETIO_MESSAGE_QUEUE: redis://redis:6379/1
      VIDEO_JSON_PATH: "/app/videos.json"
      ACTION_MODEL_PATH: "/app/app/ml_models/action_detection/weights/model-v1.pth"
      OBJECT_MODEL_PATH: "/app/app/ml_models/object_detection/weights/obj_detect_best_v5.pt"
      NVIDIA_DISABLE_REQUIRE: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./uploads:/uploads
    depends_on:
      - redis
      - celery-worker

  celery-worker:
    image: chronovortex07/celery-worker:localhost
    environment:
      SECRET_KEY: "secret"
      DEBUG_MODE: True
      UPLOAD_FOLDER: /uploads
      CLEANUP_UPLOADS: False
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_TASK_TRACK_STARTED: True
      CELERY_TRACK_STARTED: True
      SOCKETIO_MESSAGE_QUEUE: redis://redis:6379/1
      VIDEO_JSON_PATH: "/app/videos.json"
      ACTION_MODEL_PATH: "/app/app/ml_models/action_detection/weights/model-v1.pth"
      OBJECT_MODEL_PATH: "/app/app/ml_models/object_detection/weights/obj_detect_best_v5.pt"
      NVIDIA_DISABLE_REQUIRE: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
    volumes:
      - ./uploads:/uploads
    depends_on:
      - redis

  redis:
    image: "redis:bullseye"